version: "3"
services:
  learn-mongodb-server-1:
    container_name: learn-mongo-server-1
    hostname: server1
    image: learn-mongodb/member-server-1
    volumes:
     - db_data_server_1:/data/db
     - .:/repo
    ports:
     - 8888:80
     - 27111:27017
    build: ./docker
    restart: always
    command: /tmp/run_services.sh
    networks:
      app_net:
        ipv4_address: 172.16.0.11

networks:
  app_net:
    ipam:
      driver: default
      config:
        - subnet: "172.16.0.0/24"

volumes:
  db_data_server_1: {}
